"""
ml/model.py
===========
The OPTIONAL machine-learning re-ranking layer.

MODEL          Logistic Regression (scikit-learn), features standardised first.
INPUT (7)      skill_score, qualification_score, location_score, stipend_score,
               experience_score, skill_x_location, skill_squared
               -> all 0.0-1.0, produced by recommendation.build_features()
OUTPUT         P(shortlisted) - the probability a recruiter shortlists this
               student for this internship.
TRAINING DATA  ml/training_data.csv - **SYNTHETIC / DEMO DATA**, generated by
               ml/generate_training_data.py from a documented recruiter-behaviour
               model. It is NOT real student or placement data, and the UI says so.

WHY A MODEL AT ALL?
The rule engine is a linear weighted sum, so it cannot express "below a 30% skill
match nothing else rescues you" or "a great skill match in an unreachable city is
still a no". Those two effects are baked into the labels, and the squared /
interaction features let the regression pick them up. The model therefore
re-orders borderline matches; it never replaces the explanation the student sees.

If scikit-learn is not installed, every function here degrades gracefully:
`predict_probability()` returns None and the app uses the rule score alone.
"""

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(HERE, "training_data.csv")

FEATURE_NAMES = [
    "skill_score", "qualification_score", "location_score", "stipend_score",
    "experience_score", "skill_x_location", "skill_squared",
]

# Module-level cache: the model is trained once, on first use, then reused.
_STATE = {"trained": False, "pipeline": None, "info": {}}


def sklearn_available():
    try:
        import sklearn  # noqa: F401
        return True
    except Exception:
        return False


def _load_csv():
    """Read training_data.csv -> (X, y). Generates the file if it is missing."""
    if not os.path.exists(CSV_PATH):
        from ml.generate_training_data import generate
        generate(CSV_PATH)

    features, labels = [], []
    with open(CSV_PATH, newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            try:
                features.append([float(row[name]) for name in FEATURE_NAMES])
                labels.append(int(row["shortlisted"]))
            except (KeyError, TypeError, ValueError):
                continue  # skip a malformed line rather than crash the app
    return features, labels


def train():
    """
    Fit the model and cache it. Returns the info dict (also used by the UI).
    Never raises - any failure just disables the ML layer.
    """
    if _STATE["trained"]:
        return _STATE["info"]
    _STATE["trained"] = True  # only ever try once per process

    if not sklearn_available():
        _STATE["info"] = {
            "available": False,
            "reason": "scikit-learn is not installed - using the rule-based engine only.",
        }
        return _STATE["info"]

    try:
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import accuracy_score, roc_auc_score
        from sklearn.model_selection import train_test_split
        from sklearn.pipeline import Pipeline
        from sklearn.preprocessing import StandardScaler

        X, y = _load_csv()
        if len(X) < 50 or len(set(y)) < 2:
            raise ValueError("not enough training data")

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.25, random_state=42, stratify=y
        )
        pipeline = Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(max_iter=1000, random_state=42)),
        ])
        pipeline.fit(X_train, y_train)

        predictions = pipeline.predict(X_test)
        probabilities = pipeline.predict_proba(X_test)[:, 1]
        coefficients = pipeline.named_steps["clf"].coef_[0]

        _STATE["pipeline"] = pipeline
        _STATE["info"] = {
            "available": True,
            "model": "Logistic Regression (scikit-learn)",
            "features": FEATURE_NAMES,
            "target": "P(shortlisted)",
            "n_samples": len(X),
            "n_train": len(X_train),
            "n_test": len(X_test),
            "positive_rate": round(sum(y) / len(y), 3),
            "accuracy": round(float(accuracy_score(y_test, predictions)), 3),
            "roc_auc": round(float(roc_auc_score(y_test, probabilities)), 3),
            "coefficients": [
                {"feature": name, "weight": round(float(value), 3)}
                for name, value in zip(FEATURE_NAMES, coefficients)
            ],
            "data_note": "Trained on SYNTHETIC demo data (ml/training_data.csv), "
                         "not on real student or placement records.",
        }
    except Exception as error:  # pragma: no cover - defensive
        _STATE["pipeline"] = None
        _STATE["info"] = {"available": False, "reason": f"ML layer disabled ({error})."}
    return _STATE["info"]


def predict_probability(features):
    """
    P(shortlisted) for one feature vector, or None when the ML layer is off.
    `features` must be in FEATURE_NAMES order (recommendation.build_features()).
    """
    if not _STATE["trained"]:
        train()
    pipeline = _STATE["pipeline"]
    if pipeline is None or not features or len(features) != len(FEATURE_NAMES):
        return None
    try:
        return float(pipeline.predict_proba([list(features)])[0][1])
    except Exception:  # pragma: no cover - defensive
        return None


def model_info():
    """Everything the /ml-info page and the README need to describe the model."""
    if not _STATE["trained"]:
        train()
    return _STATE["info"]


if __name__ == "__main__":
    from pprint import pprint
    pprint(train())
